name: "Northestern University Libraries"
safe: true
lsi: false
pygments: true
exclude: ['Gruntfile.js', 'package.json', 'node_modules', 'README.md', 'INSTALL.md']
markdown: kramdown
parent-url: "https://northeastern.edu"
baseurl: "https://m.library.northeastern.edu/"
desktopsite: "https://library.northeastern.edu?device=desktop"
author:
  name: "Northeastern University Libraries"
primo:
  url: "https://onesearch.northeastern.edu"
  institution-code: "NEU"
  view-code: "NU"


